version: '2'
services:
  db:
    build:
      dockerfile: Dockerfile
      context: ./db
    env_file:
      - postgres_env_vars.env
    ports:
      - "5432:5432"
    command:
      postgres -c track_commit_timestamp=on
  server:
    build:
      dockerfile: Dockerfile
      context: ./server
    env_file:
      - postgres_env_vars.env
    ports:
      - "5000:5000"
    depends_on:
      - db
