version: '2.1'
services:
  redis:
    restart: "no"
  db:
    restart: "no"
    build:
      dockerfile: Dockerfile.dev
      context: ./db
    env_file:
      - dev_secrets.env
    ports:
      - "5432:5432"
    command:
      postgres -c track_commit_timestamp=on
  worker:
    restart: "no"
    env_file:
      - dev_secrets.env
    volumes:
      - ./server/:/app
      - $CLIMBICUS_AWS:/root/.aws/credentials:ro
  server:
    restart: "no"
    env_file:
      - dev_secrets.env
    depends_on:
      - db
      - worker
    environment:
      - ENV=dev
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=development
    volumes:
      - ./server/:/app
      - $CLIMBICUS_AWS:/root/.aws/credentials:ro
    command:
      "dev-server"
