version: '2.1'
services:
  db:
    restart: always
  worker:
    restart: always
  server:
    restart: always
    env_file:
      - prod_secrets.env
    environment:
      - ENV=prod
      - PYTHONUNBUFFERED=1
    command:
      "main-server"
