version: '2.1'
services:
  redis:
    restart: always
    image: redis:latest
    sysctls:
      - net.core.somaxconn=4096
  worker:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./server
    command:
      celery -A app.celery worker --loglevel=info
    depends_on:
      - redis
  server:
    restart: always
    depends_on:
      - worker
    environment:
      - ENABLE_USER_VERIFICATION=1
    build:
      dockerfile: Dockerfile
      context: ./server
    ports:
      - "5000:5000"
    entrypoint:
      - /app/entrypoint.sh
#  elk:
#    build:
#      dockerfile: Dockerfile
#      context: ./elk
#    ports:
#      - "5601:5601"
#      - "9200:9200"
#      - "5044:5044"
