name: climbicus
description: A climbing app.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  async: ^2.3.0
  intl: ^0.16.1
  image_picker: ^0.6.1+10
  camera: ^0.5.8+1
  flutter_image_compress: ^0.6.8
  flutter_image: ^3.0.0
  carousel_slider: ^1.4.1
  json_annotation: ^3.0.1
  http: ^0.12.0+2
  shared_preferences: ^0.5.6
  flutter_secure_storage: ^3.3.3
  provider: ^4.0.4
  package_info: '>=0.4.0+16 <2.0.0'
  bloc: ^3.0.0
  flutter_bloc: ^3.2.0
  get_it: ^4.0.1
  path_provider: ^1.6.8
  path: ^1.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.7.3"
  build_runner: ^1.7.4
  json_serializable: ^3.2.5

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - images/no_image.png
