name: climbicus
description: A climbing app.

version: 0.1.0+6

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  async: ^2.3.0
  intl: ^0.17.0
  image_picker: ^0.6.1+10
  camera: ^0.5.8+1
  flutter_image_compress: ^0.6.4
  flutter_image: ^3.0.0
  carousel_slider: ^1.4.1
  flutter_touch_spin: ^2.0.0-nullsafety.1
  flutter_rating_bar: ^3.0.1+1
  toggle_switch: ^0.1.8
  json_annotation: ^4.0.1
  http: ^0.13.3
  shared_preferences: ^2.0.5
  flutter_secure_storage: ^3.3.3
  provider: ^5.0.0
  package_info: '>=0.4.0+16 <2.0.0'
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  get_it: ^4.0.1
  path_provider: ^2.0.1
  path: ^1.6.4
  sentry_flutter: ^4.0.0
  device_info: ^1.0.0
  select_dialog: ^1.2.3
  device_preview: ^0.7.1
  photo_view: ^0.10.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.0
  build_runner: ^1.7.4
  json_serializable: ^4.1.1

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - images/no_image.png
