name: climbicus
description: A climbing app.

version: 0.1.0+14

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3

  async: ^2.5.0
  intl: ^0.17.0
  image_picker: ^0.7.4
  camera: ^0.8.1
  flutter_image_compress: ^1.0.0
  flutter_image: ^4.0.1
  image: ^3.0.2
  carousel_slider: ^4.0.0-nullsafety.0
  flutter_touch_spin: ^2.0.0-nullsafety.1
  flutter_rating_bar: ^4.0.0
  toggle_switch: ^0.1.9
  json_annotation: ^4.0.1
  http: ^0.13.3
  shared_preferences: ^2.0.5
  flutter_secure_storage: ^4.2.0
  provider: ^5.0.0
  package_info: ^2.0.0
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  get_it: ^7.0.0
  path_provider: ^2.0.1
  path: ^1.6.4
  sentry_flutter: ^5.0.0
  device_info: ^2.0.0
  select_dialog: ^2.0.0
  device_preview: ^0.7.1
  photo_view: ^0.11.1
  url_launcher: ^6.0.3
  permission_handler: ^7.1.0
  tutorial_coach_mark: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.0
  build_runner: ^2.0.2
  json_serializable: ^4.1.1

flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - images/no_image.png
