from app.models import Gyms, RouteImages, Routes, UserRouteLog, Users


def preload_dummy_data(db):
    db.session.add(Users(email="test@testing.com", password="testing"))
    db.session.add(Users(email="silas04@gmail.com", password="chorrera"))
    db.session.add(Users(email="keksainis@gmail.com", password="masterbates"))
    db.session.add(Gyms(name="The Castle Climbing Centre"))
    db.session.flush()
    db.session.add(Routes(gym_id=1, class_id=1, grade="6A+"))
    db.session.add(Routes(gym_id=1, class_id=2, grade="7A+"))
    db.session.add(Routes(gym_id=1, class_id=3, grade="7C+"))
    db.session.add(Routes(gym_id=1, class_id=4, grade="8A"))
    db.session.add(Routes(gym_id=1, class_id=5, grade="6B"))
    db.session.add(Routes(gym_id=1, class_id=6, grade="6C"))
    db.session.add(Routes(gym_id=1, class_id=7, grade="7B"))
    db.session.add(Routes(gym_id=1, class_id=8, grade="7B+"))
    db.session.add(Routes(gym_id=1, class_id=9, grade="6A"))
    db.session.add(Routes(gym_id=1, class_id=10, grade="6B"))
    db.session.add(Routes(gym_id=1, class_id=11, grade="7A"))
    db.session.add(Routes(gym_id=1, class_id=12, grade="6A"))
    db.session.add(Routes(gym_id=1, class_id=13, grade="6C"))
    db.session.add(Routes(gym_id=1, class_id=14, grade="5+"))
    db.session.add(Routes(gym_id=1, class_id=15, grade="6A+"))
    db.session.add(Routes(gym_id=1, class_id=16, grade="6B+"))
    db.session.add(Routes(gym_id=1, class_id=17, grade="6C+"))
    db.session.add(Routes(gym_id=1, class_id=18, grade="4+"))
    db.session.add(Routes(gym_id=1, class_id=19, grade="5+"))
    db.session.add(Routes(gym_id=1, class_id=20, grade="6A+"))
    db.session.add(Routes(gym_id=1, class_id=21, grade="6B+"))
    db.session.add(Routes(gym_id=1, class_id=22, grade="6A"))
    db.session.add(Routes(gym_id=1, class_id=23, grade="6B"))
    db.session.add(Routes(gym_id=1, class_id=24, grade="6C"))
    db.session.add(Routes(gym_id=1, class_id=25, grade="7B+"))
    db.session.add(Routes(gym_id=1, class_id=26, grade="6A"))
    db.session.add(Routes(gym_id=1, class_id=27, grade="6C"))
    db.session.add(Routes(gym_id=1, class_id=28, grade="5+"))
    db.session.add(Routes(gym_id=1, class_id=29, grade="6B+"))
    db.session.add(Routes(gym_id=1, class_id=30, grade="7B"))
    db.session.add(Routes(gym_id=1, class_id=31, grade="5"))
    db.session.add(Routes(gym_id=1, class_id=32, grade="7A+"))
    db.session.add(Routes(gym_id=1, class_id=33, grade="5"))
    db.session.add(Routes(gym_id=1, class_id=34, grade="6C"))
    db.session.add(Routes(gym_id=1, class_id=35, grade="5+"))
    db.session.add(Routes(gym_id=1, class_id=36, grade="6A+"))
    db.session.add(Routes(gym_id=1, class_id=37, grade="6C"))
    db.session.add(Routes(gym_id=1, class_id=38, grade="6A+"))
    db.session.add(Routes(gym_id=1, class_id=39, grade="6B+"))
    db.session.add(Routes(gym_id=1, class_id=40, grade="7A"))
    db.session.add(Routes(gym_id=1, class_id=41, grade="5"))
    db.session.add(Routes(gym_id=1, class_id=42, grade="5+"))
    db.session.add(Routes(gym_id=1, class_id=43, grade="6A+"))
    db.session.add(Routes(gym_id=1, class_id=44, grade="6B+"))
    db.session.add(Routes(gym_id=1, class_id=45, grade="7A"))
    db.session.flush()
    db.session.add(RouteImages(user_route_id=1, model_route_id=1, user_id=1, model_probability=0.5,
                               model_version="first_version",
                               path="placeholder"))
    db.session.add(UserRouteLog(route_id=1, user_id=1, gym_id=1, status="red-point", log_date="2019-10-10"))
    db.session.commit()
