name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: make docker-build
    - name: Run
      run: make args=-d docker-run
    - name: Tests
      run: make tests
    - name: Clean up
      run: make docker-down
