name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: make docker-build
    - name: Run
      run: make args=-d docker-up
      env:
        ENV: dev
    - name: Unit tests
      run: make tests
      env:
        ENV: dev
    - name: Load dummy data
      run: make args=recreate-db docker-run
      env:
        ENV: dev
    - name: Clean up
      run: make docker-down
      env:
        ENV: dev
