name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: make docker-build
    - name: Run
      run: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up -d
    - name: Tests
      run: make tests
    - name: Clean up
      run: make docker-down
